#!/bin/bash

if [ $(nmcli networking connectivity check) == "full" ]
then
  # Update toolbox container
  echo "--------------------" | logger -t all-system-update
  echo "--> UPDATE TOOLBOX  " | logger -t all-system-update
  echo "--------------------" | logger -t all-system-update
  if [ ! -z "$(runuser -u admin -- toolbox list | grep fedora-toolbox)" ]; then runuser -u admin -- toolbox run sudo dnf -y upgrade; fi  

  # Update flatpak apps
  echo "--------------------" | logger -t all-system-update
  echo "--> UPDATE FLATPAK  " | logger -t all-system-update
  echo "--------------------" | logger -t all-system-update
  flatpak update -y

  # Download bootc updates
  echo "--------------------" | logger -t all-system-update
  echo "--> UPDATE BOOTC    " | logger -t all-system-update
  echo "--------------------" | logger -t all-system-update
  bootc upgrade
fi
